-- 코드를 입력하세요
# 각 행의 내용들을 합쳐서 하나의 행을 만들때
SELECT CONCAT("/home/grep/src/", BOARD_ID, "/",FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (
SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) # == 아니고 =임, LIMIT 1 최상단에 있는 한개뽑을 때
ORDER BY FILE_ID DESC;
