SELECT CASE WHEN TO_CHAR(START_DATE, 'MM') < 10 THEN SUBSTR(TO_CHAR(START_DATE, 'MM'),2,1)
            ELSE TO_CHAR(START_DATE, 'MM')
       END AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
  AND CAR_ID IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
      GROUP BY CAR_ID
      HAVING COUNT(*) >= 5
  )
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY TO_CHAR(START_DATE, 'MM') ASC, CAR_ID DESC;