-- 코드를 입력하세요
-- SELECT INFO.FLAVOR, INFO.INGREDIENT_TYPE, SUM(FIRST.TOTAL_ORDER) TOTAL_ORDER
--   FROM FIRST_HALF FIRST, ICECREAM_INFO INFO
--  WHERE FIRST.FLAVOR = INFO.FLAVOR
-- GROUP BY INFO.FLAVOR, INFO.INGREDIENT_TYPE
-- ORDER BY TOTAL_ORDER ASC;


SELECT INGREDIENT_TYPE, SUM(FIRST.TOTAL_ORDER) TOTAL_ORDER
  FROM FIRST_HALF FIRST, ICECREAM_INFO INFO
 WHERE FIRST.FLAVOR = INFO.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;